# Custom values to pro environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
reloader:
  deployment:
    env:
      secret:
        # AWS SSM Parameter Store
        AWS_SSM_PARAMETER_STORE: ref+awsssm://foo/bar
        # AWS Secrets Manager
        AWS_SECRETS_MANAGER: ref+awssecrets://myteam/mykey
        # AWS S3
        AWS_S3: ref+s3://mybucket/myjsonobj#/foo/bar
        # AWS KMS
        AWS_KMS: ref+awskms://AQICAHhy...nHRHwfyC7AGZ8ek=#/foo/bar
        # Tfstate in S3 Bucket
        AWS_TFSTATE_S3: ref+tfstates3://bucket/path/to/some.tfstate/aws_vpc.main.id
