# Custom values to pro environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
reloader:
  deployment:
    env:
      secret:
        # Hashicorp Vault
        HC_VAULT: ref+vault://mykv/foo#/bar?address=https://vault1.example.com:8200
