# Custom values to dev environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
reloader:
  deployment:
    env:
      secret:
        # Google GCS
        GCP_GCS: ref+gcs://mybucket/mykey
        # GCP Secrets Manager
        GCP_SECRETS_MANAGER: ref+gcpsecrets://myproject/mysecret
        # Tfstate in GCS Bucket
        GCP_TF_TFSTATE: ref+tfstategs://bucket/path/to/some.tfstate/google_compute_disk.instance.id