# Custom values to pre environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
reloader:
  deployment:
    env:
      open:
        # AZ Key Vault
        OPEN_AZ_KEY_VAULT: ref+azurekeyvault://sops-test/sops-secret
        # Tfstate in AzureRM Blob Storage
        #OPEN_AZ_TFSTATE_SC: ref+tfstateazurerm://my_rg/my_storage_account/terraform-backend/unique.terraform.tfstate/output.virtual_network.name
      secret:
        # AZ Key Vault
        AZ_KEY_VAULT: ref+azurekeyvault://sops-test/sops-secret
        # Tfstate in AzureRM Blob Storage
        #AZ_TFSTATE_SC: ref+tfstateazurerm://my_rg/my_storage_account/terraform-backend/unique.terraform.tfstate/output.virtual_network.name
